167 add filter params
open-sauced/hot pull request #184
Opened 2022-06-16 18:48 UTC by htuerker

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

1. Added react-router dependency
2. Wrapped `App` component by `BrowserRouter` to use router functionalities into further children. 
3. Created `searchParams` state by `useSearchParams`
4. Used `activeLink` as a derived state from `searchParams` instead of a managed state.
5. Moved the handler logic into where we handle state
6. Removed unused props from `SecondaryNav`

Fixes #167 

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

![Screen Shot 2022-06-16 at 21 39 13](https://user-images.githubusercontent.com/46192266/174142194-ebecb992-a913-4fe4-b57c-327707aa0308.png)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2022-06-16 18:57 UTC, 0-vortex commented
The pull request code looks great however I was hoping we can use actual routes, not query parameters - at least that was my intention in commenting here: https://github.com/open-sauced/hot/issues/167#issuecomment-1132346093

Would you be able and willing to transform the query parameters into something like:
`localhost:3000/?filter=upvoted` into `localhost:3000/most-upvoted-repositories`?

2022-06-16 19:28 UTC, htuerker commented
> Would you be able and willing to transform the query parameters into something like: `localhost:3000/?filter=upvoted` into `localhost:3000/most-upvoted-repositories`?

This would be a little tricky but if I got correct you want to see a meaningful pathname instead of query params. So, your suggestion is to not use query parameters at all.

Instead of the button with a handler in `SecondaryNav`, we can use `<Link to="/most-upvoted-repositories />` to navigate, then parse the current pathname with a simple hash. `parsePathName("most-upvoted-repositories") ===> return "upvoted"`.

2022-06-17 14:17 UTC, htuerker commented
I delivered changes by last commit @0-vortex 

Last changes in order:

1. Replace filtering buttons with `Links`
2. `activeLink` is a derived state linked to location.
3. `activeLink` state already protected by unknown paths i.e `/some-user-given-path` defaults to `popular`
4. `limit` is a derived state linked to `searchParams`
5. `limit` state defaults `0` and `NaN` values to `25`
6. Both are generated synchronously so there's no state batching problem as I know
7. When the location changes via `SecondaryNav` links `limit` defaults to `25` (this is the reason why I changed `limit` logic)

Problems:
1. You can give any number you want as a limit in the path. But this is a pagination problem so the new API should correct this problem. We can easily update this implementation with `per_page` `page_number` logic.

2022-06-17 21:54 UTC, bdougie commented
@htuerker I think what you have works great. It is a good first step. My only suggestion is there are too many word. `most-popular-repositories` should be `popular`.

2022-06-17 21:56 UTC, bdougie requested changes

2022-06-17 21:56 UTC, bdougie commented on src/components/PostsWrap.tsx
> +  "/most-popular-repositories": "popular",
Please use the filter name instead. 

```suggestion
  "/popular": "popular",
```

2022-07-01 21:12 UTC, bdougie approved these changes
Sorry was out of town and this fell the list of things to review.

2022-07-01 21:31 UTC, merged