bug: added '_redirect' file
open-sauced/hot pull request #219
Opened 2022-07-22 18:50 UTC by shamimbinnur

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR resolves the "Page not found problem" while accessing any route with a direct link. 

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2022-07-22 18:57 UTC, 0-vortex requested changes
Please move this to the `netlify.toml` configuration file available in the root of the project:
- all the netlify configuration is stored there
- adding the redirects file to public has additional side effects

Edit links:
- https://github.com/open-sauced/hot/blob/main/netlify.toml
- https://docs.netlify.com/routing/redirects/

2022-07-24 23:50 UTC, bdougie commented
@shamimbinnur checking in on this to see if you can swap this to the toml

```
[[redirects]]
  from = "/*"
  to = "/index.html "
  status = 200
```

2022-07-25 03:12 UTC, shamimbinnur commented
> @shamimbinnur checking in on this to see if you can swap this to the toml
> 
> ```
> [[redirects]]
>   from = "/*"
>   to = "/index.html "
>   status = 200
> ```

@bdougie added this in toml file

2022-07-25 03:50 UTC, 0-vortex commented on netlify.toml
> +  to = "/index.html "
Please remove the space between `html` and `"`

2022-07-25 04:12 UTC, 0-vortex approved these changes
LGTM, merging this on beta!

2022-07-25 04:14 UTC, merged