feat: add report a bug in user dropdown
open-sauced/hot pull request #239
Opened 2022-07-27 07:20 UTC by ddsuhaimi

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
fixes #206 

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings
![image](https://user-images.githubusercontent.com/30659198/181185925-7b2953aa-3d17-4c6d-a591-d2f72a876c54.png)

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2022-07-27 18:37 UTC, bdougie commented on src/components/PrimaryNav.tsx
> +                        window.open(bugReportLink);
<a href={bugReportLink} />
  <button></button>
</a>

interesting use of window.open. Curious if there is value over using a href?

2022-07-27 20:17 UTC, bdougie commented on src/components/PrimaryNav.tsx
> +                        window.open(bugReportLink);
I suppose less lines and use of button onClick may be more accesible?

2022-07-27 21:26 UTC, bdougie requested changes
Per [this s/o](https://stackoverflow.com/questions/1667416/window-location-href-vs-clicking-on-an-anchor/1667512#1667512) answer, could you swap this to href?

2022-07-28 05:22 UTC, ddsuhaimi commented
@bdougie no problem

2022-07-28 05:31 UTC, ddsuhaimi commented
@bdougie I have updated the PR, lemme know if you need me to change anything else

2022-07-28 11:53 UTC, 0-vortex approved these changes
LGTM!

2022-07-28 11:53 UTC, 0-vortex approved these changes

2022-07-28 11:54 UTC, merged