#106: Version number and ascii art addition
open-sauced/hot pull request #322
Opened 2022-08-23 22:55 UTC by erinmikailstaples

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [x] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Please do not leave this blank 
This PR updates version as well as adds the ascii art to the index page.
-

## Related Tickets & Documents
Fixes #106
https://github.com/open-sauced/hot/issues/106

## Mobile & Desktop Screenshots/Recordings

Workflow

Set up:

Forked repo, [cloned it here.](https://github.com/erinmikailstaples/hot-add-version-number-console)
Task 1: Include [fetch version lib](https://github.com/open-sauced/open-sauced/blob/main/src/lib/appVersion.js) similar to open sauced.

Added new file under lib > appVersion.js and copied over the version page
Image

Task 2: [Add ascii art](https://github.com/open-sauced/open-sauced/blob/eb1bb9030cbc0bba6d883d5ed933e99f5488ea14/src/index.jsx#L43-L49) to the index page.

Added ascii art to the index page here:
Image

Add ascii art https://github.com/open-sauced/hot/issues/106#issuecomment-1217018904
Opened src > app.tsx + added the ascii art starting on line 13 (view below)
Image

Syncing to the [repo here](https://github.com/erinmikailstaples/hot-add-version-number-console) now.

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help
_i think i did this right... maybe?_

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2022-08-23 23:36 UTC, erinmikailstaples reviewed
Removed it in index.js + renamed PR

2022-08-24 00:41 UTC, 0-vortex requested changes
Minor changes should remove the lint issues, then running an `npm run format` should auto-apply our code formatter and make everything green! 🍕 

Doing these changes should unblock the deployment preview so you can see the version in the console - I tested locally with the proposed changes and it LGTM! 👍

2022-08-24 00:41 UTC, 0-vortex commented on src/App.tsx
> +import { version } from "../../package.json";
```
import { version } from "../package.json";
```

2022-08-24 00:41 UTC, 0-vortex commented on src/App.tsx
> + ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝  ╚═════╝╚══════╝╚═════╝%c v${version()}`,
`version` instead on `version()` - it's a string value, calling it as a string will remove the error

2022-08-24 00:41 UTC, 0-vortex commented on src/lib/appVersion.js
> +import pkg from "../../package.json";
this file is not used right now - consider getting the version from this file import in `App.tsx` or removing this file entirely

2022-08-30 21:36 UTC, bdougie commented on index.html
> +
```suggestion
```

We can remove this

2022-08-30 21:37 UTC, bdougie commented on index.html
> +
This is not needed let's removes it🙏🏾

2022-08-30 21:38 UTC, bdougie requested changes
Can you run `npm run format` locally and then push that up? It will get rid of some errors.

2022-09-08 22:32 UTC, bdougie commented
@erinmikailstaples heads up, I fixed your PR on stream and open a new one here. #332 

For context I did the following
- Ran npm run format
- Replaced the package.json version with appVersion.ts

2022-09-08 22:38 UTC, closed without merging