Myvotes placeholder
open-sauced/hot pull request #406
Opened 2022-11-29 21:03 UTC by Deadreyo

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2022-11-29 23:15 UTC, bdougie requested changes
Just a copy fix to sound a bit nicer. Everything else looks good, except I am not sure why the HotRepositories were moved. I agree with the change, but it seemed unrelated.

2022-11-29 23:15 UTC, bdougie commented on src/components/VotedRepoListWrap.tsx
> +            <h1 className="text-2xl text-center">You didn&apos;t vote on any Repositories. Your votes will appear here.</h1>
Not quite confident with this copy. My suggestion is a bit nicer for the viewers
```suggestion
            <h1 className="text-2xl text-center">Try voting on any repository. Your vote will appear here.</h1>
```

2022-11-30 17:10 UTC, 0-vortex requested changes
LGTM! 👍 

1 small change to make it perfect 🙏

2022-11-30 17:10 UTC, 0-vortex commented on src/components/VotedRepoListWrap.tsx
> +      <div className="mx-auto max-w-7xl px-4 pb-1 mt-10">
the padding bottom added here looks great but it doesn't exist on the list repositories container; definitely no change when no voted repositories, but could use the padding on the list as well to make it look 💯

2022-12-01 12:47 UTC, bdougie approved these changes
I am approving, but @0-vortex requested change is still pending.

2022-12-01 13:28 UTC, Deadreyo commented
> LGTM! 👍
> 
> 1 small change to make it perfect 🙏

done

2022-12-01 16:56 UTC, bdougie approved these changes

2022-12-01 17:28 UTC, merged