fixes: hide load more button when no more data is available
open-sauced/hot pull request #448
Opened 2023-02-14 20:04 UTC by imvedanshmehra

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR fixes issue #446  

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-02-14 22:46 UTC, TAKANOME-DEV commented
Thanks for your contribution @imvedanshmehra :pizza:

Seems like the button is still visible :thinking: 
I noticed that there is no more data after `limit === 50`. Updating the condition should fix this issue.
```js
{fetchedData.length > 0 && activeLink !== "myVotes" && limit < 50 && (//render btn)}
```

Another thing I have noticed, maybe not related to this issue, the limit in the search params is different from the one sent to the API even after removing `if (value > 25) return 50` :thinking:  (see screenshot below)

![Screenshot from 2023-02-14 22-35-35](https://user-images.githubusercontent.com/79809121/218879866-eec71d44-c31e-4013-80eb-268ebdfc8d32.png)

Any idea of what's causing this @0-vortex?

2023-02-15 14:34 UTC, 0-vortex commented
> 

Yes, this is not how limit works in general ... API has to provide a `totalPages` type of variable or an `itemCount` like ours. Fetched data length will always be limit 🍕

2023-02-18 06:27 UTC, imvedanshmehra commented
Hi @TAKANOME-DEV, the **Load More** button is now visible only when we have some data.

We can set this condition `limit <= 50` only if we are sure that the API will not return more than 50 data. Otherwise, we might not have any way to load past 50th data.

Regarding the second issue that the limit in search params is different than what we are sending to the API. I checked that locally it seems fine 🤔 (Please check the screenshot attached below).

<img width="1791" alt="Screenshot 2023-02-18 at 11 45 10 AM" src="https://user-images.githubusercontent.com/44801561/219844865-9144a5bf-a41a-4537-ba8d-8c3402b0ddb3.png">

2023-02-18 09:49 UTC, TAKANOME-DEV commented
> We can set this condition `limit <= 50` only if we are sure that the API will not return more than 50 data. Otherwise, we might not have any way to load past 50th data.
> 
Yeah, also the API returns `hasNextPage` in the `meta` object. So the button should be hidden if that property is `false`.
> I checked that locally it seems fine.
> 
Weird :thinking:  Try it with the deploy preview https://deploy-preview-448--hot-sauced-ui.netlify.app/

2023-02-18 11:03 UTC, 0-vortex requested changes
This enables the meta object:

```const { data, meta } = useRepositoriesList(RepoOrderByEnum[activeLink], limit);```

Then, the `limit` query parameter has to be changed to handle pagination:
```
const handleLoadingMore = () => {
    setSearchParams({ limit: String(limit + 10) });
  };
```

The above code needs to be fixed in order for the load more button to work, you can play with the parameters here: https://api.opensauced.pizza/#/Repository%20service/findAll

2023-02-19 07:07 UTC, imvedanshmehra commented
I noticed that 50 is the maximum limit we can pass to the `limit` query params, which means that once we have fetched all the 50 items `hasNextPage` in the `meta` should be set to `false` but was still `true` somehow. Therefore, if we relying on `hasNextPage` to show/hide the **Load More** button, it will always be shown even though we have no more data to fetch.

<img width="1409" alt="Screenshot 2023-02-19 at 12 32 26 PM" src="https://user-images.githubusercontent.com/44801561/219934002-f67686f2-83ad-40f5-aa98-ee90f96bb450.png">
<img width="1420" alt="Screenshot 2023-02-19 at 12 32 52 PM" src="https://user-images.githubusercontent.com/44801561/219934005-bf2feded-b4c0-48af-bb3a-88f520fad850.png">

2023-02-19 08:24 UTC, TAKANOME-DEV commented
> I noticed that 50 is the maximum limit we can pass to the `limit` query params, which means that once we have fetched all the 50 items `hasNextPage` in the `meta` should be set to `false` but was still `true` somehow.
> 
True, there should be a reason why the limit is fixed.
This pr should be good to go if you do the changes mentionned by `o-vortex` above and hide the button if `limit <= 50` :pizza:

2023-02-19 08:56 UTC, 0-vortex commented
> > I noticed that 50 is the maximum limit we can pass to the `limit` query params, which means that once we have fetched all the 50 items `hasNextPage` in the `meta` should be set to `false` but was still `true` somehow.
> 
> > 
> 
> True, there should be a reason why the limit is fixed.
> 
> This pr should be good to go if you do the changes mentionned by `o-vortex` above and hide the button if `limit <= 50` :pizza: 

I'm sorry but no, this is not the solution. Unless you agree to correctly implement meta, there is no incremental improvement we can do.

The load more button should disappear when the page is equal to the last page or hasNextPage is false. Has nothing to do with limit, it's just the number of items we display per page.

2023-02-19 10:34 UTC, TAKANOME-DEV commented
> I'm sorry but no, this is not the solution.
> 
Oh my bad, thanks for clarifying this :+1: 
> Unless you agree to correctly implement meta, there is no incremental improvement we can do.
>
I'll look into it, but can't promise anything

2023-03-31 15:31 UTC, OgDev-01 commented
Hey @imvedanshmehra How is this going? Have you been able to pull through?

2023-04-03 01:03 UTC, NsdHSO commented on src/components/RepoListWrap.tsx
> +  myVotes = "myVotes",
```suggestion
  myVotes = "myVotes"
```

2023-07-09 14:52 UTC, bdougie commented
We will need to approach this differently. Closing for now.

2023-07-09 14:52 UTC, closed without merging