feat: Implemented the filter logic on the nav links
open-sauced/hot pull request #57
Opened 2022-01-02 21:19 UTC by hokagedemehin

## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [x] ✨ Feature

## Description

This PR adds the filter feature on the secondary nav link so as to change the data displayed based on the link that is clicked. I will explain my thought process on how I went about completing this task

- I removed `SecondaryNav.astro` and created `SecondaryNav.jsx`. I did this because I wanted to use some react hooks to perform state management in the component
- Each nav list had a `data-name` tag with unique names of the link. I did this so as to implement conditional styling on the active link. I wanted to dynamically change the style of the active link so that when any of the links are clicked, it sets the given style that I needed on it and adjusts the rest
- In the `PostWrap.jsx` file , I added the `SecondaryNav.jsx` there instead of the `index.astro` file and also created two new components `GridDisplay.jsx` and `ListDisplay.jsx` to replace `PostGrid.jsx` and `PostList.jsx` respectively
-  Inside of the two new files is where the sorting was done based on the nav link that was clicked and also the `PostGrid.jsx` and `PostList.jsx` file was used here to render out the final data

## Related Tickets & Documents

Fixes #41 

## Mobile & Desktop Screenshots/Recordings

#### Popular nav link screenshot (Default API filter)
![Screenshot 2022-01-02 215511](https://user-images.githubusercontent.com/16826624/147889284-31b103ae-b74b-4fe9-a9a7-92f3812d5377.png)

#### Discussed nav link screenshot (Filter by issue count)
![Screenshot 2022-01-02 215526](https://user-images.githubusercontent.com/16826624/147889300-b2bc3d85-8b2f-41eb-b0b6-9e9b776561db.png)

#### Recent nav link screenshot (Filter by lowest avg_recency_score)
![Screenshot 2022-01-02 215545](https://user-images.githubusercontent.com/16826624/147889317-0f488c4d-854b-4646-bd16-452ee2fd72a6.png)

## Added tests?

- [x] 🙅 no, because they aren't needed

## Added to documentation?

- [x] 🙅 no documentation needed

2022-01-02 21:27 UTC, hokagedemehin commented
Hello @0-vortex 

Could you please review this PR and tell me what you think, if it meets the requirements of the issue?

🤞🏾🤞🏾🤞🏾

2022-01-02 22:04 UTC, 0-vortex commented
> Hello @0-vortex
> 
> Could you please review this PR and tell me what you think, if it meets the requirements of the issue?
> 
> 🤞🏾🤞🏾🤞🏾

Checked the deploy preview and the functionality matches the issue description, will give the code a second look in the morning and get back to you 🍕 

Thank you for contributing ❤️

2022-01-03 19:33 UTC, hokagedemehin commented
👀

2022-01-03 20:54 UTC, 0-vortex commented
Follow up to the initial review: other than HTML comments I am not sure how the backend/pagination would look like. @bdougie is this ok to pass with local filtering?

2022-01-04 21:52 UTC, bdougie commented
> Follow up to the initial review: other than HTML comments I am not sure how the backend/pagination would look like. @bdougie is this ok to pass with local filtering?

For now, this works since the API doesn't have pagination or anything. Quite honestly I problem I am going to punt on until we get live data on the page. 

My thought is to do sort and cache it from the API in local storage, but I have not done this personally. My experience is limited to paginated APIs like GitHub. I will open an issue on this once this is merged.

2022-01-04 22:00 UTC, bdougie requested changes
Remove the comment component and open the issue for testing filtering. Once that is done, this is good to merge.

Thanks for taking this on, just be sure to check if issues are assigned before starting the work in the future.

2022-01-05 09:49 UTC, hokagedemehin commented on src/pages/index.astro
> +    <!-- <SecondaryNav /> -->
I have removed the commented component and unused imports

2022-01-05 11:14 UTC, hokagedemehin commented on src/components/ListDisplay.jsx
> +              .map((item, i) => <PostList data={item} key={i} />)}
I have opened an issue for this PR to be tested. it is here #64 

Please could you check if it is fine by you

2022-01-05 13:32 UTC, bdougie reviewed
Best practice is to remove dead code instead of commenting it out. The ternary operators seem to be replacing these, and this comment is not providing any context that is needed.

2022-01-05 13:32 UTC, bdougie commented on src/components/SecondaryNav.jsx
> +  // console.log(activeLink);
Dead code should be deleted
```suggestion
```

2022-01-05 13:32 UTC, bdougie commented on src/components/SecondaryNav.jsx
> +              // className="hover:text-saucyRed transition-all duration-300 mr-3 sm:mr-11"
Dead code again
```suggestion
```

2022-01-05 13:32 UTC, bdougie commented on src/components/SecondaryNav.jsx
> +              // className="hover:text-saucyRed transition-all duration-300 mr-3 sm:mr-11"
```suggestion
```

2022-01-05 13:32 UTC, bdougie commented on src/components/SecondaryNav.jsx
> +              // className="hover:text-saucyRed  transition-all duration-300 mr-3 sm:mr-11"
```suggestion
```

2022-01-05 13:34 UTC, merged